project:
  type: website
  preview:
    port: 4000
website:
  title: "Ruby Peterman"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



